{% set version = "5.0.0" %}

package:
  name: eigen
  version: {{ version }}

source:
  fn: eigen-{{ version }}.tar.gz
  url: https://gitlab.com/libeigen/eigen/-/archive/{{ version }}/eigen-{{ version }}.tar.gz
  sha256: 866164d22da5d01a76921631fe949bb9d23af6ce4f151f95b47752d403fd3c96

build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make

test:
  requires:
    - {{ compiler('cxx') }}
  files:
    - test.cc

  commands:
    - test -d ${PREFIX}/include/eigen3  # [unix]
    - if not exist %PREFIX%\\Library\\include\\eigen3 exit 1  # [win]
    - if not exist %PREFIX%\\Library\\share\\pkgconfig\\eigen3.pc exit 1  # [win]

about:
  home: http://eigen.tuxfamily.org/
  license: MPL-2.0
  summary: C++ template library for linear algebra

extra:
  recipe-maintainers:
    - traversaro
    - jakirkham
    - patricksnape
    - jschueller
    - seanyen
