{% set version = "3.4.0" %}

package:
  name: eigen-split
  version: {{ version }}

source:
  fn: eigen-{{ version }}.tar.gz
  url: https://gitlab.com/libeigen/eigen/-/archive/{{ version }}/eigen-{{ version }}.tar.gz
  sha256: 8586084f71f9bde545ee7fa6d00288b264a2b7ac3607b974e54d13e7162c1c72

build:
  number: 1

outputs:
  - name: eigen
    script: build-eigen.sh  # [unix]
    script: bld-eigen.bat  # [win]
    requirements:
      build:
        - cmake
        - {{ compiler('cxx') }}
        - make
    test:
      requires:
        - {{ compiler('cxx') }}
      files:
        - test.cc
      commands:
        - test -d ${PREFIX}/include/eigen3  # [unix]
        - if not exist %PREFIX%\\Library\\include\\eigen3 exit 1  # [win]
        - if not exist %PREFIX%\\Library\\share\\pkgconfig\\eigen3.pc exit 1  # [win]

  # The eigen-abi logic is discussed in https://github.com/conda-forge/eigen-feedstock/pull/41, still a work in progress
  - name: eigen-abi
    # The version of eigen-abi is composed by the eigen version, and the value used for EIGEN_MAX_ALIGN_BYTES
    version: {{ version }}.{{ eigen_max_align_bytes }}
    build:
      run_exports:
        - {{ pin_subpackage('eigen-abi', max_pin='x.x.x.x') }}
      run_constrained:
        - eigen =={{ version }}
        - x86_64-microarch-level >=1,<3 # [x86_64 and eigen_max_align_bytes == "16"]
    requirements:
      run:
        - x86_64-microarch-level ==3 # [x86_64 and eigen_max_align_bytes == "32"]
        - x86_64-microarch-level ==4 # [x86_64 and eigen_max_align_bytes == "64"] 
    test:
      commands:
        - echo "This is a metapackage, no test is necessary."

about:
  home: http://eigen.tuxfamily.org/
  license: MPL-2.0
  summary: C++ template library for linear algebra
  description: |
      This feedstock builds two different conda packages:
      * `eigen`: the eigen header only library ifself.
      * `eigen-abi`: this a meta-package should be added as a dependency for packages that use contain C++ compiled libraries that use eigen in their public headers.


extra:
  recipe-maintainers:
    - traversaro
    - jakirkham
    - patricksnape
    - jschueller
    - seanyen
