{% set version = "3.3.8" %}

package:
  name: eigen
  version: {{ version }}

source:
  fn: eigen-{{ version }}.tar.gz
  url: https://gitlab.com/libeigen/eigen/-/archive/{{ version }}/eigen-{{ version }}.tar.gz
  sha256: 146a480b8ed1fb6ac7cd33fec9eb5e8f8f62c3683b3f850094d9d5c35a92419a
  patches:
    - bug2011.patch
    - paradiso.patch

build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - make

test:
  requires:
    - {{ compiler('cxx') }}
  files:
    - test.cc

  commands:
    - test -d ${PREFIX}/include/eigen3  # [unix]
    - if not exist %PREFIX%\\Library\\include\\eigen3 exit 1  # [win]
    - if not exist %PREFIX%\\Library\\share\\pkgconfig\\eigen3.pc exit 1  # [win]

about:
  home: http://eigen.tuxfamily.org/
  license: MPL-2.0
  summary: C++ template library for linear algebra

extra:
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - jschueller
    - seanyen
