{% set version = "3.3.4" %}

package:
  name: eigen
  version: {{ version }}

source:
  fn: eigen-{{ version }}.tar.gz
  url: http://bitbucket.org/eigen/eigen/get/{{ version }}.tar.gz
  sha256: 4286e8f1fabbd74f7ec6ef8ef31c9dbc6102b9248a8f8327b04f5b68da5b05e1

build:
  number: 0

requirements:
  build:
    - cmake
    - python  # [win]

test:
  files:
    - test.cc

  commands:
    - test -d ${PREFIX}/include/eigen3  # [unix]
    - if not exist %PREFIX%\\Library\\include\\eigen3 exit 1  # [win]

about:
  home: http://eigen.tuxfamily.org/
  license: MPL2
  license_file: COPYING.MPL2
  summary: C++ template library for linear algebra

extra:
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - jschueller
