schema_version: 1

context:
  version: 3.4.0

recipe:
  name: eigen-split
  version: ${{ version }}

source:
  - url: https://gitlab.com/libeigen/eigen/-/archive/${{ version }}/eigen-${{ version }}.tar.gz
    sha256: 8586084f71f9bde545ee7fa6d00288b264a2b7ac3607b974e54d13e7162c1c72

build:
  number: 1

outputs:
  - package:
      name: eigen
      version: ${{ version }}
    build:
      script:
        - if: unix
          then: build_eigen.sh
        - if: win
          then: build_eigen.bat

    requirements:
      build:
        - cmake
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - ninja
    tests:
      - files:
          recipe:
            - test.cc
        requirements:
          build:
            - ${{ compiler('cxx') }}
        script:
          - if: unix
            then:
              - ${CXX} -I${PREFIX}/include -o test test.cc
              - ./test
          - if: win
            then:
              - "%CXX% -I%PREFIX%\\Library\\include -o test.exe test.cc"
              - test.exe
      - script:
          - if: unix
            then:
              - test -d ${PREFIX}/include/eigen3
          - if: win
            then:
              - if not exist %PREFIX%\\Library\\include\\eigen3 exit 1
              - if not exist %PREFIX%\\Library\\share\\pkgconfig\\eigen3.pc exit 1
          - cmake-package-check Eigen3 --targets Eigen3::Eigen
        requirements:
          run:
            - cmake-package-check
            - ${{ compiler('c') }}
            - ${{ compiler('cxx') }}

  # The eigen-abi and eigen-abi-devel logic is discussed in detail recipe/README.md
  - package:
      name: eigen-abi-devel
      # The version of eigen-abi is composed by the eigen version, and the eigen_abi_profile value
      version: ${{ version }}.${{ eigen_abi_profile }}
    requirements:
      run_exports:
        - ${{ pin_subpackage('eigen-abi', upper_bound='x.x.x.x') }}
      run_constraints:
        - if: x86_64 and eigen_max_align_bytes == "16"
          then:
            - x86_64-microarch-level >=1,<3
      run:
        - ${{ pin_subpackage('eigen', upper_bound='x.x.x') }}
        - ${{ pin_subpackage('eigen-abi', upper_bound='x.x.x.x') }}
        - if: x86_64 and eigen_max_align_bytes == "32"
          then: x86_64-microarch-level 3.*
        - if: x86_64 and eigen_max_align_bytes == "64"
          then: x86_64-microarch-level 4.*
    tests:
      - files:
          recipe:
            - test_abi/test_abi.cc
            - test_abi/CMakeLists.txt
        script:
          - cmake -GNinja -Stest_abi -Bbuild_test_abi -DEXPECTED_EIGEN_MAX_ALIGN_BYTES=${{ eigen_max_align_bytes }}
          - cmake --build build_test_abi
        requirements:
          run:
            - cmake
            - ninja
            - ${{ compiler('cxx') }}

  - package:
      name: eigen-abi
      # The version of eigen-abi is composed by the eigen version, and eigen_abi_profile value
      version: ${{ version }}.${{ eigen_abi_profile }}
    tests:
      - script:
          - echo "This is a metapackage, no test is necessary."


about:
  homepage: http://eigen.tuxfamily.org/
  license: MPL-2.0
  license_file: COPYING.MPL2
  summary: C++ template library for linear algebra

extra:
  recipe-maintainers:
    - traversaro
    - jakirkham
    - patricksnape
    - jschueller
    - seanyen
