schema_version: 1

context:
  version: "5.0.1"

package:
  name: eigen
  version: ${{ version }}

source:
  - url: https://gitlab.com/libeigen/eigen/-/archive/${{ version }}/eigen-${{ version }}.tar.gz
    sha256: e9c326dc8c05cd1e044c71f30f1b2e34a6161a3b6ecf445d56b53ff1669e3dec

build:
  number: 0
  script:
    - if: unix
      then: build.sh
    - if: win
      then: build.bat

requirements:
  build:
    - cmake
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - if: unix
      then:
         - ${{ compiler('fortran') }}
    - ninja

tests:
  - files:
      recipe:
        - test.cc
    requirements:
      build:
        - ${{ compiler('cxx') }}
    script:
      - if: unix
        then:
          - ${CXX} -I${PREFIX}/include -o test test.cc
          - ./test
      - if: win
        then:
          - "%CXX% -I%PREFIX%\\Library\\include -o test.exe test.cc"
          - test.exe
  - script:
      - if: unix
        then:
          - test -d ${PREFIX}/include/eigen3
      - if: win
        then:
          - if not exist %PREFIX%\\Library\\include\\eigen3 exit 1
          - if not exist %PREFIX%\\Library\\share\\pkgconfig\\eigen3.pc exit 1

about:
  homepage: http://eigen.tuxfamily.org/
  license: MPL-2.0
  license_file: COPYING.MPL2
  summary: C++ template library for linear algebra

extra:
  recipe-maintainers:
    - traversaro
    - jakirkham
    - patricksnape
    - jschueller
    - seanyen
